### ISSUE TITLE
Remove JSON requirement from documentation

### ISSUE THREAD

**Issue by garak** [blancks/fast-jsonpatch-php#1]
The README is reporting in the "requirements" section:

>JSON extension enabled in PHP

This is useless, since the JSON extension is bundled inside php itself since 8.0 and this library requires php 8.1 or above.

By the way, you could even remove the entire "requirements" section, since it's already declared in the composer file (and all the versions below 8.1 are currently out of support)

**Comment by blancks** [comment]
That's a good point, thanks! 
I will remove the Requirements section altogether but i think i'll use a "php version" badge instead.
People may casually read the documentation from the github project instead of packagist and i want to make crystal clear that older versions are not supported

**Comment by garak** [comment]
Good idea about the badge. May I suggest using https://poser.pugx.org/ for it?

**Comment by blancks** [comment]
Love it! Thank you for the suggestion 😄

**Comment by blancks** [comment]
@garak it seems i'm having a bad time using the badges, they won't display on github but they works nicely in my PHPStorm's preview. I'm surely missing something here, do you have any idea on what might be ?

![immagine](https://github.com/user-attachments/assets/bdd272a4-539d-414d-b247-002a8ed80f5c)

**Comment by blancks** [comment]
Just figured out that the github proxy url didn't liked the https redirect of the badge url. 
I fixed that and [shared](https://github.com/PUGX/badge-poser/issues/1195#issuecomment-2308465865) my findings in the issue tracker of PUGX/badge-poser
